### PR TITLE
Ensure unique salt

### PR DESCRIPTION
**Pull request by ceeram**
Composer install will now generate salt in separate file config/salt.php

This change also needs a change in cakebox, to be able to recreate the box with the same salt.

### CODE REVIEW

**Comment by ceeram** [comment]
Refs #57

**Comment by bravo-kernel** [comment]
Should bootstrap.cli not also be updated so the Shells use the same salt?

**Comment by ceeram** [comment]
No, cli loads both files ;)

2015-03-24 16:13 GMT+01:00 bravo-kernel <notifications@github.com>:

**Comment by bravo-kernel** [comment]
Aha, I see now

**Comment by bravo-kernel** [comment]
Nice one, looking good. Merging as Travis seems to be back in business again. Will fix PHPCS myself if need be.

**Comment by bravo-kernel** [comment]
Your welcome ;)

https://github.com/alt3/cakebox-console/commit/4bcdcac93f77fa01b0ee58f14bddda141f76d64c

**Pull request merged**
