### PR TITLE
Do not show cakebox as application

### PR DESCRIPTION
**Pull request by bravo-kernel**
PR for issue https://github.com/alt3/cakebox-console/issues/68

### CODE REVIEW

**Comment by ceeram** [comment]
Nice

**Comment by bravo-kernel** [comment]
Looks like Travis is having some problems, let me retry

**Comment by bravo-kernel** [comment]
ps: not changing the empty donut spot until a good solution/usage comes along.

**Comment by ceeram** [comment]
Travis was having issues with hhvm and composer earlier as well. Wrt donut,
i cannot come up with something usefull. I guess not showing anything is
fine for now
Op 24 mrt. 2015 18:14 schreef "bravo-kernel" <notifications@github.com>:

**Pull request merged**
