### PR TITLE
Added an initial ugly styled message

### PR DESCRIPTION
**Pull request by ceeram**
i know it looks ugly, had to start somewhere, you can finish it if you like @bravo-kernel

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Good start and... don't worry about the markup. I do think it deservers a littlle more :heart: before we merge this

- see the specs at #68 
- we should probably also do something with the empty donut (maybe a placeholder image)

**Comment by ceeram** [comment]
The undefined variable was not created by this change. It is fixed in dev branch already.

**Comment by ceeram** [comment]
why close?

**Comment by bravo-kernel** [comment]
Didn't meet the specs at https://github.com/alt3/cakebox-console/issues/68. Creating a new PR

**Pull request closed without merging**
